### DISCUSSION TITLE
Hit Multiple snags following rust-wasm tutorial. Hoping for some help

### DISCUSSION THREAD

**Discussion by Rennzie** [wasm-bindgen/wasm-bindgen#2848] [Q&A]
Hi, I'm hoping someone could help me out. I've been working through the RustWasm book `wasm-game-of-life` tutorial but hit a snag. 

When I compile Rust to wasm and import it into Javascript the struct turns into a class fine but I cannot invoke any of its methods. The console shows a `Universe.new is not a function` error - which is weird because the generated .d.ts file includes the method. If I invoke  the class with `new Universe()` I get another error: `Error: null pointer passed to rust`. Finally I tried adding a `#[wasm_bindgen(constructor)]` macro to the `Universe.new()` struct impl which resulted in wasm-pack build throwing  yet another error `Caused by: failed to execute wasm-bindgen: exited with exit status: 101`. 

I've googled all these errors and can't find a way to move forward. It'd love if someone could take a look at my code (https://github.com/Rennzie/wasm-game-of-life) and help me out? 

I've upgrade to the latest edition of rust (2021) and all my packages in cargo.toml are at latest:

```toml
[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["Sean.Rennie <rnnsea001@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.79"


[dev-dependencies]
wasm-bindgen-test = "0.3.29"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

```
