### DISCUSSION TITLE
Using js-sys crate in WASM

### DISCUSSION THREAD

**Discussion by Kapelianovych** [wasm-bindgen/wasm-bindgen#2934] [Q&A]
Hello! I'm exploring Conway's game of life tutorial and trying to implement random Universe generation. However, after inserting the

```rs
use js_sys::Math;
```

the command `wasm-pack build` successfully finishes building the `pkg`, but the webpage shows nothing. Also, there is no error that can help.

I have the `js-sys` cargo declared in the _Cargo.toml_.

```toml
[dependencies]
js-sys = "0.3.57"
wasm-bindgen = "0.2.80"
```
