### DISCUSSION TITLE
How can I look at old documentation?

### DISCUSSION THREAD

**Discussion by miketwenty1** [wasm-bindgen/wasm-bindgen#3785] [Q&A]
### Summary
https://docs.rs allows you to pick a release version of crate and see a snapshot of what was available. Is there anyway to do this with wasm-bindgen or web-sys? It seems only the most current version is available.

My goal ultimately though is to see if there was a substitute for the `UserActivation` struct at the time of v0.2.87 / web-sys crate: `0.3.64`.

Interested in this: 
https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.UserActivation.html#method.is_active

Currently failing to patch in this way (below), so was trying to look at the docs of an older version that I'm needing to use for another dependency "bevy".
```toml
[patch.crates-io]
web-sys = { git = "https://github.com/rustwasm/wasm-bindgen.git", branch = "main", features = [
    "UserActivation",
] }
# This doesn't seem to work for me, I can't resolve web_sys::UserActivation struct
```
