### DISCUSSION TITLE
wasm-bindgen introduces potential panics into code

### DISCUSSION THREAD

**Discussion by newpavlov** [wasm-bindgen/wasm-bindgen#4203] [Q&A] [answered]
Let's say I have a crate with the following Cargo.toml and src/lib.rs:
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[lib]
name = "foo"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.89", default-features = false }

[profile.release]
panic = "abort"
```
```rust
#[no_mangle]
pub extern "C" fn add(a: u32, b: u32) -> u32 {
    a.wrapping_add(b)
}
```
Compiling it results in a small and compact WASM file as expected.

But trying to use `wasm-bindgen`, even without doing anything with it:
```rust
use wasm_bindgen::prelude::wasm_bindgen;

#[no_mangle]
pub extern "C" fn add(a: u32, b: u32) -> u32 {
    a.wrapping_add(b)
}

#[wasm_bindgen]
extern "C" {}
```

results in a much bigger file, which includes allocator and potential panic paths. This not only bloats size of generated WASM files, but also makes it harder to write robust code which attempts to "prove" that it does not contain any potential panics.

Is this behavior intended and expected?
