### DISCUSSION TITLE
The init function was not found after building

### DISCUSSION THREAD

**Discussion by OlalalalaO** [wasm-bindgen/wasm-bindgen#4398] [Q&A]
### Summary

After run `wasm-pack build --target bundler`, the `init` function was not found in hello-wasm.d.ts

#### Code
```rust
use wasm_bindgen::prelude::*;


#[wasm_bindgen]
extern {
    pub fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
```
#### dependencies
```toml
[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
[dependencies]
wasm-bindgen = "0.2.99"
```
#### version
```shell 
rustc --version                 
rustc 1.83.0 (90b35a623 2024-11-26)
```
```shell 
wasm-pack -V                    
wasm-pack 0.13.1
```
#### ?
hello-wasm.d.ts
```ts
/* tslint:disable */
/* eslint-disable */
export function greet(name: string): void;
```
Why is only the `greet` function exported and not the `init` function? What should I do?
